### ISSUE TITLE
/stock lookup throws NPE on invalid argument

### ISSUE THREAD

**Issue by DarkEyeDragon** [maldahleh/stock-market#10]
```
[07:28:20 WARN]: [StockMarket] Plugin StockMarket v1.3.0 generated an exception while executing task 1157
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.15.2.jar:git-Paper-132]
        at com.google.common.cache.LocalCache.put(LocalCache.java:4363) ~[patched_1.15.2.jar:git-Paper-132]
        at com.google.common.cache.LocalCache$LocalManualCache.put(LocalCache.java:5077) ~[patched_1.15.2.jar:git-Paper-132]
        at com.maldahleh.stockmarket.stocks.StockManager.getStock(StockManager.java:85) ~[?:?]
        at com.maldahleh.stockmarket.inventories.lookup.LookupInventory.lambda$openInventory$1(LookupInventory.java:85) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-132]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-132]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

Should be an easy fix. I'd PR it myself but seems like you have a custom maven repo of the YahooFinanceAPI which i don't have access to

**Comment by 2hakjv** [comment]
Changing YahooFinanceAPI to version 3.15.0 is also available for build
How do I fix NPE? I get the same error
I want to fix it, but I don't know Java

```
[22:23:26] [Server thread/WARN]: [StockMarket] Task #94 for StockMarket v1.3.0 generated an exception
java.lang.NullPointerException: null
	at com.maldahleh.stockmarket.inventories.lookup.LookupInventory.lambda$openInventory$0(LookupInventory.java:105) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"003c5b3"]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Tuinity-"003c5b3"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.15.2.jar:git-Tuinity-"003c5b3"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"003c5b3"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.15.2.jar:git-Tuinity-"003c5b3"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Tuinity-"003c5b3"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
