### ISSUE TITLE
v3.0.0-beta.4 Plugin doesn't work at all

### ISSUE THREAD

**Issue by markaabo** [maldahleh/stock-market#95]
## Expected Behavior

The plugin to not crash on startup and work :)

## Current Behavior

Crashes and doesn't work

## Environment

The server is running on paper, using java 16

* Project Version: v3.0.0-beta.3
* PaperMC Version:  paper-1.17.1-388
* Java Version: Java 16

## Failure Information

The plugin crashes immediatly on startup with this error message:
`[12:59:36 INFO]: [StockMarket] Loading 1 libraries... please wait
[12:59:36 INFO]: [StockMarket] Loaded library C:\_FilezillaFolders\_Server2PC-SERVERS\Swind3ls - SwindSMP (TestingSMP) 1.17.1\libraries\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar
[12:59:36 ERROR]: Could not load 'plugins\StockMarket.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/maldahleh/stockmarket/StockMarket, offset=6
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer$$Lambda$3673/0x00000000a2eaeeb0.run(Unknown Source) ~[app:?]
        at java.lang.Thread.run(Thread.java:853) ~[?:?]
Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/maldahleh/stockmarket/StockMarket, offset=6
        at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:489) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:450) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:197) ~[patched_1.17.1.jar:git-Paper-388]
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1208) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1123) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-388]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1106) ~[?:?]
        at java.lang.Class.forNameImpl(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:420) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Paper-388]
        ... 8 more`

### Steps to Reproduce

Install paper, install plugin, startup server.

## Checklist

- [X] I am running the latest version
- [X] I checked the documentation
- [X] I checked to make sure that this issue has not already been filed

**Comment by markaabo** [comment]
Tested new version: v3.0.0-beta.4

Still not working at all

**Comment by markaabo** [comment]
Is the plugin still under development and ready to use or? @maldahleh

**Comment by maldahleh** [comment]
@markaabo, sorry just saw this issue; the plugin is compiled in Java 17 but I should bump that down to 16, will try to publish a version sometime today.

**Comment by maldahleh** [comment]
@markaabo I published a new beta build with Java 16, though it is still not tested. I will try to complete testing on it this weekend.

**Comment by markaabo** [comment]
> @markaabo I published a new beta build with Java 16, though it is still not tested. I will try to complete testing on it this weekend.

It seems to be loading in now, but with the 1.18 update, it has broken. it is also broken for me like Sidelo98 described and showed in #113 

Hopefully a fix can be made soon, would really like to use the plugin :-)

**Comment by markaabo** [comment]
The issue is still relevent, and the plugin is still not working

**Comment by markaabo** [comment]
@maldahleh Any news on fixing it?
